# Generated by Django 4.1.4 on 2023-03-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arc',
            name='name',
            field=models.CharField(default='New Arc', max_length=30, verbose_name='Arc name'),
        ),
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default='New Character', max_length=30, verbose_name='Character name'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='name',
            field=models.CharField(blank=True, default='New Event', max_length=30, null=True, verbose_name='Event name'),
        ),
        migrations.AlterField(
            model_name='paradigm',
            name='name',
            field=models.CharField(default='New Paradigm', max_length=20, verbose_name='Paradigm name'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(default='New Parameter', max_length=20, verbose_name='Parameter name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='New User', max_length=30, verbose_name='Username'),
        ),
    ]
